### ISSUE TITLE
Did not get error using fileset.upload()

### ISSUE THREAD

**Issue by kajabremer** [entailor/pytailor#25]
I used the code below to upload a fileset. I had a typo in the file name, but I didn't get an error from tailor, so it still started the workflow. Is this a new feature? It failed at every task using the base_model because it did not find the file specified.

```
fileset = FileSet(project)
fileset.upload(base_model=[base_model_file])
```

**Comment by agrav** [comment]
Thats strange, this is what happend when I try this with the latest version of pytailor:
``````
prj = Project.from_name("Test")
fileset = FileSet(prj)
fileset.upload(my_file_tag=["a_non_existing_file.txt"])
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.2.3\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\AudunGravdalJohansen\Devel\pytailor\src\pytailor\api\fileset.py", line 31, in upload
    check_local_files_exist(files)
  File "C:\Users\AudunGravdalJohansen\Devel\pytailor\src\pytailor\utils.py", line 213, in check_local_files_exist
    raise FileNotFoundError(f"Could not find local file: {filename}.")
FileNotFoundError: Could not find local file: a_non_existing_file.txt.
``````
